robot_planner:
  ros__parameters:
    domain_file: "path/to/domain.pddl"
    domain_template_topic: "/pddl_domain_template"
    problem_file: "path/to/problem.pddl"

goal_gateway:
  ros__parameters:
    goal_topic: "/robot_planner/goal"
    status_topic: "/robot_planner/goal_status"
    set_goal_service: "/problem_expert/add_problem_goal"
    allow_parallel: false

pddl_aggregator:
  ros__parameters:
    map_pddl_topic: "/pddl/map"
    people_topic: ""
    objects_topic: ""
    robots_topic: ""
    problem_pddl_topic: "/pddl/problem"
    domain_file: "pddl/domain.pddl"
    problem_output_file: "/tmp/problem.pddl"
    problem_name: ""
    domain_name: ""
    people_predicate: "person_at"
    objects_predicate: ""
    robots_predicate: "at"
