location_coordinates:
  room_1:
    x: 432
    y: 80
    theta: 0.0
  room_2:
    x: 229
    y: 312
    theta: 0.0
  room_3:
    x: 350
    y: 235
    theta: 0.0
  room_4:
    x: 299
    y: 43
    theta: 0.0
  room_5:
    x: 67
    y: 62
    theta: 0.0
  room_6:
    x: 298
    y: 22
    theta: 0.0
  room_7:
    x: 116
    y: 29
    theta: 0.0
  room_8:
    x: 167
    y: 23
    theta: 0.0
  room_9:
    x: 243
    y: 54
    theta: 0.0
  room_10:
    x: 237
    y: 204
    theta: 0.0
